### ISSUE TITLE
Request: Adding a License File

### ISSUE THREAD

**Issue by danteu** [coffeemakingtoaster/zerolog-loki-hook#1]
Hi,

thanks for the clean implementation and your [write-up](https://blog.mi.hdm-stuttgart.de/index.php/2024/02/29/combining-zerolog-loki/). I'm interested in using this package and it would be good to have clarity about its license status. Could you add a license file to the project?

Best regards,
Daniel

**Comment by coffeemakingtoaster** [comment]
Hey @danteu ,

thanks for bringing that up, I totally forgot about the license.
Anyway I added a license so all should be good to go now 🚀 

Best regards,
Max
